language: php

php:
- 5.5
- 5.6
- hhvm

notifications:
  email: false

before_script:
- composer self-update
- composer install --prefer-source --no-interaction --ignore-platform-reqs --dev

script: vendor/bin/phpunit

deploy:
  provider: heroku
  api_key:
    secure: MpWpj4sX9KwhcWq3mKk82xwRxVleujK1ijiowoAweRCWjZ4q7MZW70B6J5+EFiAzEWBEbpIzxGA4OMU5/Vjqo5U9AvNHA0MUK4/EDdT61cyriVWX4enAiMt4IyVI0+GCju+KAJJllDDpX/TgIWhQJnkIaPV4RbJZW+zO0ymGAJQ=
  app:
    develop: thai-lotto-staging
    master: thai-lotto
  on:
    php: 5.6
